# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1310, 822)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(140, 160, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(150, 380, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(290, 40, 301, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.btn_gen_keys = QtWidgets.QPushButton(Form)
        self.btn_gen_keys.setGeometry(QtCore.QRect(680, 60, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_gen_keys.setFont(font)
        self.btn_gen_keys.setObjectName("btn_gen_keys")
        self.btn_sign = QtWidgets.QPushButton(Form)
        self.btn_sign.setGeometry(QtCore.QRect(300, 650, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_sign.setFont(font)
        self.btn_sign.setObjectName("btn_sign")
        self.btn_verify = QtWidgets.QPushButton(Form)
        self.btn_verify.setGeometry(QtCore.QRect(690, 640, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_verify.setFont(font)
        self.btn_verify.setObjectName("btn_verify")
        self.txt_info = QtWidgets.QTextEdit(Form)
        self.txt_info.setGeometry(QtCore.QRect(260, 160, 611, 221))
        self.txt_info.setObjectName("txt_info")
        self.txt_sign = QtWidgets.QTextEdit(Form)
        self.txt_sign.setGeometry(QtCore.QRect(260, 400, 611, 221))
        self.txt_sign.setObjectName("txt_sign")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Infomation:"))
        self.label_4.setText(_translate("Form", "Signature:"))
        self.label_5.setText(_translate("Form", "ECC CIPHER"))
        self.btn_gen_keys.setText(_translate("Form", "Generate Keys"))
        self.btn_sign.setText(_translate("Form", "Sign"))
        self.btn_verify.setText(_translate("Form", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
